[package]
name = "cosmos_id_cli"
version = "0.1.0"
authors = ["Amos Elmaliah <amosel@gmail.com>"]
edition = "2021"

[dependencies]
k256 = { version = "0.11.6", features = ["ecdsa"] }
clap = { version = "4.1.8", features = ["derive"] }
rand_core = "0.6.4"
cosmos_id = { path = "../cosmos_id" }
